version: '3.4'

services:
  crypto-index:
    image: pecheriere/crypto-index:latest
    build: .
    secrets:
      - mdb_user
      - mdb_password
      - mdb_host

secrets:
  mdb_user:
    external: true
  mdb_password:
    external: true
  mdb_host:
    external: true